plugins {
	id 'org.springframework.boot' version '3.3.0'
	id 'java'
}

apply plugin: 'io.spring.dependency-management'

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '17'

repositories {
	mavenCentral()
}

def opentelemetryVersion = "1.48.0"
def opentelemetryInstrumentationVersion = "2.13.3"

dependencies {
	// tag::actuator[]
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	// end::actuator[]
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.5.0'
	// tag::tests[]
	testImplementation('org.springframework.boot:spring-boot-starter-test')
	// end::tests[]

	implementation platform("io.opentelemetry:opentelemetry-bom:${opentelemetryVersion}")
	implementation platform("io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom:${opentelemetryInstrumentationVersion}")
	implementation "io.opentelemetry:opentelemetry-api",
		"io.opentelemetry:opentelemetry-sdk",
		"io.opentelemetry.instrumentation:opentelemetry-instrumentation-annotations"
	implementation group: 'org.apache.logging.log4j', name: 'log4j-api', version: '2.23.1'
	implementation group: 'org.apache.logging.log4j', name: 'log4j-core', version: '2.23.1'

}

test {
	useJUnitPlatform()
}
